=== danielbarion/L2JBlueHeart/game/config/sunrise/event/language/event_lang_en.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="localization">
		<xs:annotation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="message" maxOccurs="unbounded"
					minOccurs="0">
					<xs:annotation>
					</xs:annotation>
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="xs:string" name="id" use="optional" />
								<xs:attribute type="xs:string" name="text" use="optional" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="lang" />
			<xs:attribute type="xs:float" name="version" />
			<xs:attribute type="xs:string" name="author" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== danielbarion/L2JBlueHeart/game/config/sunrise/event/language/event_lang_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<localization lang="English" version="2.21" author="L2][Sunrise Team" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./event_lang_en.xsd">

	<!-- ============================================ -->
	<!-- Basic engine messages and names added in 2.0 -->
	
	<message id="system_warning" text="You have received a warning. If you receive %i more warnings, you will be unable to participate in event. Warnings decrease by 1 every day." />
	<message id="system_warningsDecreased" text="Your event warnings count has been decreased by 1, now you have %i." />
	
	<message id="registering_jail" text="You cannot register from the jail." />
	<message id="registering_siege" text="You cannot register while in siege." />
	<message id="registering_duel" text="You cannot register while you are dueling." />
	<message id="registering_olympiad" text="You cannot register while you are in the olympiad." />
	<message id="registering_karma" text="You cannot register if you have karma." />
	<message id="registering_cursedWeapon" text="You cannot register with a cursed weapon." />
	<message id="registering_storemode" text="You cannot register while in store mode." />
	
	<message id="registering_highLevel" text="Your level is higher than the max allowed level." />
	<message id="registering_lowLevel" text="Your level is lower than the min required level." />
	<message id="registering_sameIp" text="There are too many registered players in the event using the same IP as you." />
	<message id="registering_status" text="Your status doesn't allow you to participate the event." />
	<message id="registering_notRegState" text="The event is no in the registration state, you cannot register now." />
	<message id="registering_alreadyRegistered" text="You are already registered to another event." />
	<message id="registering_warningPoints" text="You cannot join the event because you have more than allowed count of Warning points. Warning points decrease every day by 1 and you gain them by doing unallowed things on events, such as disconnecting or trying to exploit. If you have more than %i points, you won't be allowed to participate in event. You currently have %i warning points." />
	<message id="registering_notAllowed" text="You may not register to this event." />
	<message id="registering_buffs" text="You might also want to select some buffs for the event." />
	<message id="registering_registered" text="You have successfully registered to the event!" />
	<message id="registering_registered2" text="You have successfully registered to %s event!" />
	<message id="registering_fail" text="You failed to register to the event." />
	<message id="registering_full" text="The event is already full." />
	<message id="registering_timeCheckFail" text="You have to wait at least %i minutes to join this event again." />
	<message id="registering_noInstance" text="No event instance was found for you." />
	<message id="registering_notEnoughtPlayers" text="There are not enought players in your instance to start the event." />
	<message id="registering_timeCheckFailed" text="You cannot register now. Try it again later." />
	<message id="registering_party" text="You must have a party to join the event." />
	<message id="registering_noParty" text="You are not in the party." />
	<message id="registering_partyLeader" text="Only party leaders can register their parties to the event." />
	<message id="registering_partyLeader_unregister" text="Only party leaders can unregister their parties from the event." />
	<message id="registering_partyMembers" text="You need exactly %i members in your party to join the event." />
	<message id="registering_partyCantRegister" text="Your party does not meet requirements to participate in this event." />
	<message id="registering_party_memberAlreadyRegistered" text="Player %s is already registered to another event." />
	<message id="registering_party_timeCheckFail" text="Player %s cannot register cause of the delay he has to wait to join this event again." />
	<message id="registering_party_noHealer" text="Healers and buffers are not allowed on this mini event." />
	<message id="registering_afterDisconnect_true" text="Welcome back. You are being teleported back to your previous event." />
	<message id="registering_afterDisconnect_false" text="The engine could not teleport you back to your previous event anymore. The event has propably ended already or was full." />
	
	<message id="registered_first_type1" text="You are one of the first %i registered players, if you win the event, you will get some extra rewards!" />
	<message id="registered_first_type2" text="You are one of the first %i registered players, in the end of the event, you will get some extra rewards!" />
	
	<message id="unregistering_cantUnregister" text="Unregistering is not allowed here." />
	<message id="unregistering_notRegistered" text="You are not registered!" />
	<message id="unregistering_cant" text="You cannot unregister now." />
	<message id="unregistering_unregistered" text="You have been unregistered from the event." />
	<message id="unregistering_unregistered2" text="You have been unregistered from %s event." />
	<message id="unregistering_unregistered_partyBig" text="You have been unregistered from %s event because your party is too big now." />
	<message id="unregistering_memberKicked" text="Player %s was kicked from your team. He has done something against the rules of the event." />
	<message id="unregistering_memberKicked_anotherEvent" text="Player %s was kicked from your team because he has registered to another event." />
	<message id="unregistering_memberKicked_leftParty" text="Player %s was kicked from your team because he left your party." />
	
	<message id="observing_gameEnded" text="This game has already ended." />
	<message id="observing_cant" text="Your status doesn not allow you to observe a match." />
	<message id="observing_alreadyRegistered" text="You are already register to an event." />
	<message id="observing_noSpawn" text="No spawn was found for you. You cannot spectate this event." />
	
	<message id="announce_eventStarted" text="Registration for event %s has been opened." />
	<message id="announce_npcPos" text="The registration NPC is available in %s." />
	<message id="announce_moreInfoInCb" text="More informations in Community Board." />
	<message id="announce_regAborted" text="Registration has been aborted by a GM." />
	<message id="announce_eventAborted" text="The event has been aborted by GM." />
	<message id="announce_noInstance" text="The event could not be started due to lack of players in instances." />
	
	<message id="announce_timeleft_min" text="%i minutes left to register." />
	<message id="announce_timeleft_sec" text="%i seconds left to register." />
	
	<message id="announce_regClosed" text="Registration has been closed." />
	<message id="announce_lackOfParticipants" text="The event has been aborted due to lack of participants." />
	<message id="announce_started" text="The event has started!" />
	<message id="announce_teleport10sec" text="You will be teleported to the event in 10 seconds." />
	<message id="announce_teleportBack10sec" text="You will be teleported back in 10 seconds." />
	<message id="announce_end" text="The event has ended." />
	<message id="announce_alldisconnected" text="All enemy teams have disconnected. The event has been aborted." />
	
	<message id="event_choosingInstance" text="You will play in event instance %s." />
	<message id="event_revive" text="You will be respawned in %i seconds." />
	<message id="event_firstBlood" text="First blood on this event is caused by killer %s!" />
	<message id="event_mysteriousError" text="Sorry, an error occured in the event engine. It had to be aborted, we are working on a fix." />
	<message id="event_countdown_sec" text="%i seconds left till the event ends." />
	<message id="event_countdown_min" text="%i minutes left till the event ends." />
	<message id="event_extraReward" text="You receive extra rewards becuase you were one of the first %i registered players." />
	<message id="event_announceScore" text="%i. %s - %i score." />
	<message id="event_announceScore_includeKills" text="%i. %s - %i score, %i kills." />
	
	<message id="event_afkWarning" text="You have been inactive on this event for %i seconds. If you continue for the next %i seconds, your rewards might be lowered in end of the event." />
	<message id="event_afkWarning_kill" text="You have been inactive on this event for %i seconds. If you continue for the next %i seconds, you will be killed!" />
	<message id="event_afkMarked" text="You are now marked as AFK. Your rewards from this event might be lowered." />
	<message id="event_afkMarked_andDied" text="Noob %s has gone afk and is now dead." />
	<message id="event_afkDurationInfo" text="You have been AFK for %i minute(s)." />
	
	<message id="event_disconnect_team" text="All players from team %s disconnected." />
	<message id="event_disconnect_all" text="All enemy players have disconnected. The event has been aborted." />
	<message id="game_playerDisconnected" text="Player %s disconnected from the match." />
	<message id="game_playerDisconnected2" text="Your opponent %s disconnected from the match." />
	<message id="game_teamDisconnected" text="%s disconnected from the match." />
	
	<message id="event_itemNotAllowed" text="This item is not allowed on this event." />
	<message id="event_skillNotAllowed" text="This skill is not allowed on this event." />
	<message id="event_petsNotAllowed" text="Pets are not allowed on this event." />
	<message id="event_summonsNotAllowed" text="Summons are not allowed on this event." />
	
	<message id="event_ffa_announceWinner1" text="%s has won the event." />
	<message id="event_ffa_announceWinner2_part1" text="%s and" />
	<message id="event_ffa_announceWinner2_part2" text="have won the match." />
