=== danielbarion/L2JBlueHeart/game/data/xsd/armorSets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="set" maxOccurs="unbounded" minOccurs="1">
					<xs:complexType>
						<xs:sequence maxOccurs="1" minOccurs="1">
							<xs:element name="chest" maxOccurs="1" minOccurs="1">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="legs" maxOccurs="2" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="head" maxOccurs="2" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="gloves" maxOccurs="2" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="feet" maxOccurs="2" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="shield" maxOccurs="2" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="skill" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
									<xs:attribute name="level" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="shield_skill" maxOccurs="2" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
									<xs:attribute name="level" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="enchant6skill" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
									<xs:attribute name="level" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="int" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="val" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="str" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="val" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="con" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="val" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="men" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="val" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="dex" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="val" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="wit" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="val" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" use="required" type="xs:positiveInteger" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== danielbarion/L2JBlueHeart/game/data/xml/stats/armorsets/s80_dynasty.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/armorSets.xsd">
	<!-- S80 Dynasty Armor Sets -->
	<set id="65">
		<chest id="9417" /> <!-- Dynasty Breast Plate - Shield Master -->
		<legs id="9421" /> <!-- Dynasty Gaiters -->
		<legs id="11512" /> <!-- Dynasty Gaiters -->
		<head id="9422" /> <!-- Dynasty Helmet -->
		<head id="11557" /> <!-- Dynasty Helmet -->
		<gloves id="9423" /> <!-- Dynasty Gauntlet - Heavy -->
		<gloves id="11513" /> <!-- Dynasty Gauntlet -->
		<feet id="9424" /> <!-- Dynasty Boots - Heavy -->
		<feet id="11526" /> <!-- Dynasty Boots -->
		<shield id="9441" /> <!-- Dynasty Shield -->
		<shield id="11532" /> <!-- Dynasty Shield -->
		<skill id="3006" level="1" /> <!-- Equip Set Items -->
		<skill id="3348" level="1" /> <!-- Dynasty Breastplate -->
		<shield_skill id="3417" level="1" /> <!-- Equipped with Shield -->
		<enchant6skill id="3623" level="1" /> <!-- Enchant Heavy Armor (S Grade) -->
		<str val="-2" />
		<con val="2" />
	</set>
	<set id="66">
		<chest id="9418" /> <!-- Dynasty Breast Plate - Weapon Master -->
		<legs id="9421" /> <!-- Dynasty Gaiters -->
		<legs id="11512" /> <!-- Dynasty Gaiters -->
		<head id="9422" /> <!-- Dynasty Helmet -->
		<head id="11557" /> <!-- Dynasty Helmet -->
		<gloves id="9423" /> <!-- Dynasty Gauntlet - Heavy -->
		<gloves id="11513" /> <!-- Dynasty Gauntlet -->
		<feet id="9424" /> <!-- Dynasty Boots - Heavy -->
		<feet id="11526" /> <!-- Dynasty Boots -->
		<skill id="3006" level="1" /> <!-- Equip Set Items -->
		<skill id="3349" level="1" /> <!-- Dynasty Breastplate -->
		<enchant6skill id="3623" level="1" /> <!-- Enchant Heavy Armor (S Grade) -->
		<str val="2" />
		<con val="-2" />
	</set>
	<set id="67">
		<chest id="9419" /> <!-- Dynasty Breast Plate - Force Master -->
		<legs id="9421" /> <!-- Dynasty Gaiters -->
		<legs id="11512" /> <!-- Dynasty Gaiters -->
		<head id="9422" /> <!-- Dynasty Helmet -->
		<head id="11557" /> <!-- Dynasty Helmet -->
		<gloves id="9423" /> <!-- Dynasty Gauntlet - Heavy -->
		<gloves id="11513" /> <!-- Dynasty Gauntlet -->
		<feet id="9424" /> <!-- Dynasty Boots - Heavy -->
		<feet id="11526" /> <!-- Dynasty Boots -->
		<skill id="3006" level="1" /> <!-- Equip Set Items -->
		<skill id="3350" level="1" /> <!-- Dynasty Breastplate -->
		<enchant6skill id="3623" level="1" /> <!-- Enchant Heavy Armor (S Grade) -->
		<str val="1" />
		<con val="-2" />
		<dex val="1" />
	</set>
	<set id="68">
		<chest id="9420" /> <!-- Dynasty Breast Plate - Bard -->
		<legs id="9421" /> <!-- Dynasty Gaiters -->
		<legs id="11512" /> <!-- Dynasty Gaiters -->
		<head id="9422" /> <!-- Dynasty Helmet -->
		<head id="11557" /> <!-- Dynasty Helmet -->
		<gloves id="9423" /> <!-- Dynasty Gauntlet - Heavy -->
		<gloves id="11513" /> <!-- Dynasty Gauntlet -->
		<feet id="9424" /> <!-- Dynasty Boots - Heavy -->
		<feet id="11526" /> <!-- Dynasty Boots -->
		<skill id="3006" level="1" /> <!-- Equip Set Items -->
		<skill id="3351" level="1" /> <!-- Dynasty Breastplate -->
		<enchant6skill id="3623" level="1" /> <!-- Enchant Heavy Armor (S Grade) -->
		<str val="2" />
		<con val="-2" />
	</set>
	<set id="69">
		<chest id="9426" /> <!-- Dynasty Leather Armor - Dagger Master -->
		<legs id="9428" /> <!-- Dynasty Leather Leggings -->
		<legs id="11516" /> <!-- Dynasty Leather Leggings -->
		<head id="9429" /> <!-- Dynasty Leather Helmet -->
		<head id="11525" /> <!-- Dynasty Leather Helmet -->
		<gloves id="9430" /> <!-- Dynasty Leather Gloves - Light -->
		<gloves id="11515" /> <!-- Dynasty Leather Gloves -->
		<feet id="9431" /> <!-- Dynasty Leather Boots - Light -->
		<feet id="11524" /> <!-- Dynasty Leather Boots -->
		<skill id="3006" level="1" /> <!-- Equip Set Items -->
		<skill id="3352" level="1" /> <!-- Dynasty Leather Armor -->
		<enchant6skill id="3624" level="1" /> <!-- Enchant Light Armor (S Grade) -->
		<con val="-2" />
		<dex val="2" />
	</set>
	<set id="70">
		<chest id="9427" /> <!-- Dynasty Leather Armor - Bow Master -->
		<legs id="9428" /> <!-- Dynasty Leather Leggings -->
		<legs id="11516" /> <!-- Dynasty Leather Leggings -->
		<head id="9429" /> <!-- Dynasty Leather Helmet -->
		<head id="11525" /> <!-- Dynasty Leather Helmet -->
		<gloves id="9430" /> <!-- Dynasty Leather Gloves - Light -->
		<gloves id="11515" /> <!-- Dynasty Leather Gloves -->
		<feet id="9431" /> <!-- Dynasty Leather Boots - Light -->
		<feet id="11524" /> <!-- Dynasty Leather Boots -->
		<skill id="3006" level="1" /> <!-- Equip Set Items -->
		<skill id="3353" level="1" /> <!-- Dynasty Leather Armor -->
		<enchant6skill id="3624" level="1" /> <!-- Enchant Light Armor (S Grade) -->
		<con val="-2" />
		<dex val="2" />
	</set>
	<set id="71">
		<chest id="9433" /> <!-- Dynasty Tunic - Healer -->
		<legs id="9437" /> <!-- Dynasty Stockings -->
		<legs id="11558" /> <!-- Dynasty Stockings -->
		<head id="9438" /> <!-- Dynasty Circlet -->
		<head id="11539" /> <!-- Dynasty Circlet -->
		<gloves id="9439" /> <!-- Dynasty Gloves - Robe -->
		<gloves id="11514" /> <!-- Dynasty Gloves -->
		<feet id="9440" /> <!-- Dynasty Shoes - Robe -->
		<feet id="11533" /> <!-- Dynasty Shoes -->
		<skill id="3006" level="1" /> <!-- Equip Set Items -->
		<skill id="3354" level="1" /> <!-- Dynasty Tunic -->
		<enchant6skill id="3625" level="1" /> <!-- Enchant Robe (S Grade) -->
		<int val="-2" />
		<men val="2" />
	</set>
	<set id="72">
		<chest id="9434" /> <!-- Dynasty Tunic - Enchanter -->
		<legs id="9437" /> <!-- Dynasty Stockings -->
		<legs id="11558" /> <!-- Dynasty Stockings -->
		<head id="9438" /> <!-- Dynasty Circlet -->
		<head id="11539" /> <!-- Dynasty Circlet -->
		<gloves id="9439" /> <!-- Dynasty Gloves - Robe -->
		<gloves id="11514" /> <!-- Dynasty Gloves -->
		<feet id="9440" /> <!-- Dynasty Shoes - Robe -->
		<feet id="11533" /> <!-- Dynasty Shoes -->
		<skill id="3006" level="1" /> <!-- Equip Set Items -->
		<skill id="3355" level="1" /> <!-- Dynasty Tunic -->
		<enchant6skill id="3625" level="1" /> <!-- Enchant Robe (S Grade) -->
		<int val="-2" />
		<men val="2" />
	</set>
	<set id="73">
		<chest id="9435" /> <!-- Dynasty Tunic - Summoner -->
		<legs id="9437" /> <!-- Dynasty Stockings -->
		<legs id="11558" /> <!-- Dynasty Stockings -->
		<head id="9438" /> <!-- Dynasty Circlet -->
		<head id="11539" /> <!-- Dynasty Circlet -->
		<gloves id="9439" /> <!-- Dynasty Gloves - Robe -->
		<gloves id="11514" /> <!-- Dynasty Gloves -->
		<feet id="9440" /> <!-- Dynasty Shoes - Robe -->
		<feet id="11533" /> <!-- Dynasty Shoes -->
		<skill id="3006" level="1" /> <!-- Equip Set Items -->
		<skill id="3356" level="1" /> <!-- Dynasty Tunic -->
		<enchant6skill id="3625" level="1" /> <!-- Enchant Robe (S Grade) -->
		<int val="-2" />
		<men val="2" />
	</set>
	<set id="74">
		<chest id="9436" /> <!-- Dynasty Tunic - Wizard -->
		<legs id="9437" /> <!-- Dynasty Stockings -->
		<legs id="11558" /> <!-- Dynasty Stockings -->
		<head id="9438" /> <!-- Dynasty Circlet -->
		<head id="11539" /> <!-- Dynasty Circlet -->
		<gloves id="9439" /> <!-- Dynasty Gloves - Robe -->
		<gloves id="11514" /> <!-- Dynasty Gloves -->
		<feet id="9440" /> <!-- Dynasty Shoes - Robe -->
		<feet id="11533" /> <!-- Dynasty Shoes -->
		<skill id="3006" level="1" /> <!-- Equip Set Items -->
		<skill id="3357" level="1" /> <!-- Dynasty Tunic -->
		<enchant6skill id="3625" level="1" /> <!-- Enchant Robe (S Grade) -->
		<int val="1" />
		<men val="-2" />
		<wit val="1" />
	</set>
	<set id="82">
		<chest id="9416" /> <!-- Dynasty Breast Plate -->
		<legs id="9421" /> <!-- Dynasty Gaiters -->
		<legs id="11512" /> <!-- Dynasty Gaiters -->
		<head id="9422" /> <!-- Dynasty Helmet -->
		<head id="11557" /> <!-- Dynasty Helmet -->
		<gloves id="9423" /> <!-- Dynasty Gauntlet - Heavy -->
		<gloves id="11513" /> <!-- Dynasty Gauntlet -->
		<feet id="9424" /> <!-- Dynasty Boots - Heavy -->
		<feet id="11526" /> <!-- Dynasty Boots -->
		<shield id="9441" /> <!-- Dynasty Shield -->
		<shield id="11532" /> <!-- Dynasty Shield -->
		<skill id="3006" level="1" /> <!-- Equip Set Items -->
		<skill id="3412" level="1" /> <!-- Dynasty Breastplate -->
		<shield_skill id="3417" level="1" /> <!-- Equipped with Shield -->
		<enchant6skill id="3623" level="1" /> <!-- Enchant Heavy Armor (S Grade) -->
		<str val="1" />
		<con val="-1" />
	</set>
	<set id="83">
		<chest id="9425" /> <!-- Dynasty Leather Armor -->
		<legs id="9428" /> <!-- Dynasty Leather Leggings -->
		<legs id="11516" /> <!-- Dynasty Leather Leggings -->
		<head id="9429" /> <!-- Dynasty Leather Helmet -->
		<head id="11525" /> <!-- Dynasty Leather Helmet -->
		<gloves id="9430" /> <!-- Dynasty Leather Gloves - Light -->
		<gloves id="11515" /> <!-- Dynasty Leather Gloves -->
		<feet id="9431" /> <!-- Dynasty Leather Boots - Light -->
		<feet id="11524" /> <!-- Dynasty Leather Boots -->
		<skill id="3006" level="1" /> <!-- Equip Set Items -->
		<skill id="3413" level="1" /> <!-- Dynasty Leather Armor -->
		<enchant6skill id="3624" level="1" /> <!-- Enchant Light Armor (S Grade) -->
		<con val="-1" />
		<dex val="1" />
	</set>
	<set id="84">
		<chest id="9432" /> <!-- Dynasty Tunic -->
		<legs id="9437" /> <!-- Dynasty Stockings -->
		<legs id="11558" /> <!-- Dynasty Stockings -->
		<head id="9438" /> <!-- Dynasty Circlet -->
		<head id="11539" /> <!-- Dynasty Circlet -->
		<gloves id="9439" /> <!-- Dynasty Gloves - Robe -->
		<gloves id="11514" /> <!-- Dynasty Gloves -->
		<feet id="9440" /> <!-- Dynasty Shoes - Robe -->
		<feet id="11533" /> <!-- Dynasty Shoes -->
		<skill id="3006" level="1" /> <!-- Equip Set Items -->
		<skill id="3416" level="1" /> <!-- Dynasty Tunic -->
		<enchant6skill id="3625" level="1" /> <!-- Enchant Robe (S Grade) -->
		<int val="-1" />
		<men val="1" />
	</set>
	<set id="85">
		<!-- NOTE: This Set uses skill 3414 (3350 is retail typo) -->
		<chest id="10126" /> <!-- Dynasty Leather Armor - Force Master -->
