=== danielbarion/L2JBlueHeart/game/data/xsd/fishes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="fish" maxOccurs="278" minOccurs="1">
					<xs:complexType>
						<xs:attribute name="cheatingProb" type="xs:decimal" use="required" />
						<xs:attribute name="combatDuration" type="xs:positiveInteger" use="required" />
						<xs:attribute name="fishBiteRate" type="xs:decimal" use="required" />
						<xs:attribute name="fishGrade" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="fish_easy" />
									<xs:enumeration value="fish_hard" />
									<xs:enumeration value="fish_normal" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="fishGroup" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="easy_swift" />
									<xs:enumeration value="easy_ugly" />
									<xs:enumeration value="easy_wide" />
									<xs:enumeration value="fish_box" />
									<xs:enumeration value="hard_swift" />
									<xs:enumeration value="hard_ugly" />
									<xs:enumeration value="hard_wide" />
									<xs:enumeration value="hs_fish" />
									<xs:enumeration value="swift" />
									<xs:enumeration value="ugly" />
									<xs:enumeration value="wide" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="fishGuts" type="xs:decimal" use="required" />
						<xs:attribute name="fishHp" type="xs:positiveInteger" use="required" />
						<xs:attribute name="fishId" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:positiveInteger">
									<xs:minInclusive value="1" />
									<xs:maxInclusive value="278" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="fishLengthRate" type="xs:decimal" use="required" />
						<xs:attribute name="fishLevel" type="xs:positiveInteger" use="required" />
						<xs:attribute name="fishMaxLength" type="xs:nonNegativeInteger" use="required" />
						<xs:attribute name="gutsCheckProbability" type="xs:decimal" use="required" />
						<xs:attribute name="gutsCheckTime" type="xs:positiveInteger" use="required" />
						<xs:attribute name="hpRegen" type="xs:decimal" use="required" />
						<xs:attribute name="itemId" type="xs:positiveInteger" use="required" />
						<xs:attribute name="itemName" type="xs:normalizedString" use="required" />
						<xs:attribute name="startCombatTime" type="xs:positiveInteger" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== danielbarion/L2JBlueHeart/game/data/xml/stats/fishing/fishes.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/fishes.xsd">
	<fish fishId="1" itemId="6411" itemName="Small Nimble Green Fish" fishGroup="swift" fishLevel="1" fishBiteRate="100.0" fishGuts="50.0" fishHp="100" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="4.0" startCombatTime="20" combatDuration="24" gutsCheckTime="5" gutsCheckProbability="50.0" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="2" itemId="6412" itemName="Small Ugly Green Fish" fishGroup="ugly" fishLevel="1" fishBiteRate="100.0" fishGuts="50.2" fishHp="116" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="4.0" startCombatTime="20" combatDuration="27" gutsCheckTime="5" gutsCheckProbability="50.2" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="3" itemId="6413" itemName="Small Pudgy Green Fish" fishGroup="wide" fishLevel="1" fishBiteRate="100.0" fishGuts="50.4" fishHp="132" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="4.0" startCombatTime="20" combatDuration="31" gutsCheckTime="5" gutsCheckProbability="50.4" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="4" itemId="6414" itemName="Nimble Green Fish" fishGroup="swift" fishLevel="2" fishBiteRate="100.0" fishGuts="50.6" fishHp="150" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="6.0" startCombatTime="20" combatDuration="25" gutsCheckTime="5" gutsCheckProbability="50.6" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="5" itemId="6415" itemName="Ugly Green Fish" fishGroup="ugly" fishLevel="2" fishBiteRate="100.0" fishGuts="50.8" fishHp="168" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="6.0" startCombatTime="20" combatDuration="28" gutsCheckTime="5" gutsCheckProbability="50.8" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="6" itemId="6416" itemName="Pudgy Green Fish" fishGroup="wide" fishLevel="2" fishBiteRate="100.0" fishGuts="51.0" fishHp="188" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="6.0" startCombatTime="20" combatDuration="31" gutsCheckTime="5" gutsCheckProbability="51.0" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="7" itemId="6417" itemName="Large Nimble Green Fish" fishGroup="swift" fishLevel="3" fishBiteRate="100.0" fishGuts="51.2" fishHp="208" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="8.0" startCombatTime="20" combatDuration="26" gutsCheckTime="5" gutsCheckProbability="51.2" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="8" itemId="6418" itemName="Large Ugly Green Fish" fishGroup="ugly" fishLevel="3" fishBiteRate="100.0" fishGuts="51.4" fishHp="230" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="8.0" startCombatTime="20" combatDuration="29" gutsCheckTime="5" gutsCheckProbability="51.4" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="9" itemId="6419" itemName="Large Pudgy Green Fish" fishGroup="wide" fishLevel="3" fishBiteRate="100.0" fishGuts="51.6" fishHp="252" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="8.0" startCombatTime="20" combatDuration="32" gutsCheckTime="5" gutsCheckProbability="51.6" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="10" itemId="6420" itemName="Small Jade Nimble Fish" fishGroup="swift" fishLevel="4" fishBiteRate="100.0" fishGuts="51.8" fishHp="276" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="10.0" startCombatTime="20" combatDuration="28" gutsCheckTime="5" gutsCheckProbability="51.8" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="11" itemId="6421" itemName="Small Jade Ugly Fish" fishGroup="ugly" fishLevel="4" fishBiteRate="100.0" fishGuts="52.0" fishHp="300" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="10.0" startCombatTime="20" combatDuration="31" gutsCheckTime="5" gutsCheckProbability="52.0" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="12" itemId="6422" itemName="Small Jade Fat Fish" fishGroup="wide" fishLevel="4" fishBiteRate="100.0" fishGuts="52.2" fishHp="310" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="10.0" startCombatTime="20" combatDuration="32" gutsCheckTime="5" gutsCheckProbability="52.2" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="13" itemId="6423" itemName="Jade Nimble Fish" fishGroup="swift" fishLevel="5" fishBiteRate="100.0" fishGuts="52.4" fishHp="320" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="11.0" startCombatTime="20" combatDuration="30" gutsCheckTime="5" gutsCheckProbability="52.4" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="14" itemId="6424" itemName="Jade Ugly Fish" fishGroup="ugly" fishLevel="5" fishBiteRate="100.0" fishGuts="52.6" fishHp="330" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="11.0" startCombatTime="20" combatDuration="31" gutsCheckTime="4" gutsCheckProbability="52.6" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="15" itemId="6425" itemName="Jade Fat Fish" fishGroup="wide" fishLevel="5" fishBiteRate="100.0" fishGuts="52.8" fishHp="340" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="11.0" startCombatTime="20" combatDuration="32" gutsCheckTime="4" gutsCheckProbability="52.8" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="16" itemId="6426" itemName="Big Jade Nimble Fish" fishGroup="swift" fishLevel="6" fishBiteRate="100.0" fishGuts="53.0" fishHp="350" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="12.0" startCombatTime="20" combatDuration="30" gutsCheckTime="4" gutsCheckProbability="53.0" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="17" itemId="6427" itemName="Big Jade Ugly Fish" fishGroup="ugly" fishLevel="6" fishBiteRate="100.0" fishGuts="53.2" fishHp="360" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="12.0" startCombatTime="20" combatDuration="31" gutsCheckTime="4" gutsCheckProbability="53.2" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="18" itemId="6428" itemName="Big Jade Fat Fish" fishGroup="wide" fishLevel="6" fishBiteRate="100.0" fishGuts="53.4" fishHp="370" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="12.0" startCombatTime="20" combatDuration="32" gutsCheckTime="4" gutsCheckProbability="53.4" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="19" itemId="6429" itemName="Small Blue Nimble Fish" fishGroup="swift" fishLevel="7" fishBiteRate="100.0" fishGuts="53.6" fishHp="380" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="12.0" startCombatTime="20" combatDuration="31" gutsCheckTime="4" gutsCheckProbability="53.6" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="20" itemId="6430" itemName="Small Blue Ugly Fish" fishGroup="ugly" fishLevel="7" fishBiteRate="100.0" fishGuts="53.8" fishHp="390" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="13.0" startCombatTime="20" combatDuration="31" gutsCheckTime="4" gutsCheckProbability="53.8" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="21" itemId="6431" itemName="Small Blue Fat Fish" fishGroup="wide" fishLevel="7" fishBiteRate="100.0" fishGuts="54.0" fishHp="400" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="13.0" startCombatTime="20" combatDuration="32" gutsCheckTime="4" gutsCheckProbability="54.0" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="22" itemId="6432" itemName="Blue Nimble Fish" fishGroup="swift" fishLevel="8" fishBiteRate="100.0" fishGuts="54.2" fishHp="410" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="13.0" startCombatTime="20" combatDuration="31" gutsCheckTime="4" gutsCheckProbability="54.2" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="23" itemId="6433" itemName="Blue Ugly Fish" fishGroup="ugly" fishLevel="8" fishBiteRate="100.0" fishGuts="54.4" fishHp="420" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="13.0" startCombatTime="20" combatDuration="32" gutsCheckTime="4" gutsCheckProbability="54.4" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="24" itemId="6434" itemName="Blue Fat Fish" fishGroup="wide" fishLevel="8" fishBiteRate="100.0" fishGuts="54.6" fishHp="430" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="14.0" startCombatTime="20" combatDuration="31" gutsCheckTime="4" gutsCheckProbability="54.6" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="25" itemId="6435" itemName="Big Blue Nimble Fish" fishGroup="swift" fishLevel="9" fishBiteRate="100.0" fishGuts="54.8" fishHp="506" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="17.0" startCombatTime="20" combatDuration="29" gutsCheckTime="4" gutsCheckProbability="54.8" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="26" itemId="6436" itemName="Big Blue Ugly Fish" fishGroup="ugly" fishLevel="9" fishBiteRate="100.0" fishGuts="55.0" fishHp="518" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="17.0" startCombatTime="20" combatDuration="30" gutsCheckTime="4" gutsCheckProbability="55.0" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="27" itemId="6437" itemName="Big Blue Fat Fish" fishGroup="wide" fishLevel="9" fishBiteRate="100.0" fishGuts="55.2" fishHp="529" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="17.0" startCombatTime="20" combatDuration="31" gutsCheckTime="4" gutsCheckProbability="55.2" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="28" itemId="6438" itemName="Small Yellow Nimble Fish" fishGroup="swift" fishLevel="10" fishBiteRate="100.0" fishGuts="55.4" fishHp="541" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="18.0" startCombatTime="20" combatDuration="30" gutsCheckTime="4" gutsCheckProbability="55.4" cheatingProb="0.0" fishGrade="fish_normal" />
	<fish fishId="29" itemId="6439" itemName="Small Yellow Ugly Fish" fishGroup="ugly" fishLevel="10" fishBiteRate="100.0" fishGuts="55.6" fishHp="552" fishMaxLength="30000" fishLengthRate="10.0" hpRegen="18.0" startCombatTime="20" combatDuration="30" gutsCheckTime="4" gutsCheckProbability="55.6" cheatingProb="0.0" fishGrade="fish_normal" />
