=== danielbarion/L2JBlueHeart/game/data/xsd/fishingMonsters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="fishingMonster" maxOccurs="8" minOccurs="1">
					<xs:complexType>
						<xs:attribute name="fishingMonsterId" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:positiveInteger">
									<xs:minInclusive value="1" />
									<xs:maxInclusive value="65535" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="probability" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:positiveInteger">
									<xs:minInclusive value="1" />
									<xs:maxInclusive value="100" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="userMaxLevel" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:positiveInteger">
									<xs:minInclusive value="1" />
									<xs:maxInclusive value="85" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="userMinLevel" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:positiveInteger">
									<xs:minInclusive value="1" />
									<xs:maxInclusive value="85" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== danielbarion/L2JBlueHeart/game/data/xml/stats/fishing/fishingMonsters.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/fishingMonsters.xsd">
	<fishingMonster userMinLevel="6" userMaxLevel="15" fishingMonsterId="18319" probability="5" />
	<fishingMonster userMinLevel="16" userMaxLevel="25" fishingMonsterId="18320" probability="5" />
	<fishingMonster userMinLevel="26" userMaxLevel="35" fishingMonsterId="18321" probability="5" />
	<fishingMonster userMinLevel="36" userMaxLevel="45" fishingMonsterId="18322" probability="5" />
	<fishingMonster userMinLevel="46" userMaxLevel="55" fishingMonsterId="18323" probability="5" />
	<fishingMonster userMinLevel="56" userMaxLevel="65" fishingMonsterId="18324" probability="5" />
	<fishingMonster userMinLevel="66" userMaxLevel="75" fishingMonsterId="18325" probability="5" />
	<fishingMonster userMinLevel="76" userMaxLevel="85" fishingMonsterId="18326" probability="5" />
</list>
