=== danielbarion/L2JBlueHeart/game/data/xsd/instance.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="instance">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="activityTime" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:positiveInteger"
							use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="allowSummon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:boolean" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="emptyDestroyTime" minOccurs="0"
					maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:positiveInteger"
							use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="PvPInstance" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:boolean" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="showTimer" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:boolean" use="required" />
						<xs:attribute name="increase" type="xs:boolean" use="optional" />
						<xs:attribute name="text" type="xs:normalizedString" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element name="spawnPoints" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Location" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="x" type="xs:int" use="required" />
									<xs:attribute name="y" type="xs:int" use="required" />
									<xs:attribute name="z" type="xs:int" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="startPosType" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="FIXED" />
									<xs:enumeration value="RANDOM" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="exitPoint" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="x" type="xs:int" use="required" />
						<xs:attribute name="y" type="xs:int" use="required" />
						<xs:attribute name="z" type="xs:int" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="reenter" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="reset" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="day">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="Monday" />
												<xs:enumeration value="Tuesday" />
												<xs:enumeration value="Wednesday" />
												<xs:enumeration value="Thursday" />
												<xs:enumeration value="Friday" />
												<xs:enumeration value="Saturday" />
												<xs:enumeration value="Sunday" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="time" type="xs:long" />
									<xs:attribute name="hour" type="xs:positiveInteger" />
									<xs:attribute name="minute" type="xs:positiveInteger" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="additionStyle">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="NONE" />
									<xs:enumeration value="ON_INSTANCE_ENTER" />
									<xs:enumeration value="ON_INSTANCE_FINISH" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="removeBuffs" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="skill" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:integer" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="type">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="ALL" />
									<xs:enumeration value="WHITELIST" />
									<xs:enumeration value="BLACKLIST" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="doorlist" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="door" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="doorId" type="xs:positiveInteger"
										use="required" />
									<xs:attribute name="default_status">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="open" />
												<xs:enumeration value="close" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="random_time" type="xs:integer" />
									<xs:attribute name="open_time" type="xs:integer" />
									<xs:attribute name="close_time" type="xs:integer" />
									<xs:attribute name="level" type="xs:nonNegativeInteger" />
									<xs:attribute name="open_method" type="xs:nonNegativeInteger" />
									<xs:attribute name="targetable" type="xs:boolean" />
									<xs:attribute name="check_collision" type="xs:boolean" />
									<xs:attribute name="clanhall_id" type="xs:positiveInteger" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="spawnlist" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="group" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element name="spawn" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="amount" type="xs:positiveInteger" />
												<xs:attribute name="heading" type="xs:integer"
													use="required" />
												<xs:attribute name="npcId" type="xs:positiveInteger"
													use="required" />
												<xs:attribute name="onKillDelay" type="xs:nonNegativeInteger" />
												<xs:attribute name="respawn" type="xs:nonNegativeInteger"
													use="required" />
												<xs:attribute name="respawnRandom" type="xs:nonNegativeInteger" />
												<xs:attribute name="allowRandomWalk" type="xs:boolean" />
												<xs:attribute name="x" type="xs:integer" use="required" />
												<xs:attribute name="y" type="xs:integer" use="required" />
												<xs:attribute name="z" type="xs:integer" use="required" />
												<xs:attribute name="areaName" type="xs:normalizedString" />
												<xs:attribute name="globalMapId" type="xs:positiveInteger" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:normalizedString"
										use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:normalizedString"
				use="required" />
			<xs:attribute name="ejectTime" type="xs:positiveInteger" />
			<xs:attribute name="allowRandomWalk" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== danielbarion/L2JBlueHeart/game/data/xml/instances/PartyDuel.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance name="coliseum" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/instance.xsd">
	<activityTime val="30" />
	<allowSummon val="false" />
	<spawnPoints startPosType="FIXED">
		<Location x="148786" y="46368" z="-3414" />
		<Location x="148786" y="46454" z="-3414" />
		<Location x="148786" y="46549" z="-3414" />
		<Location x="148786" y="46652" z="-3414" />
		<Location x="148786" y="46745" z="-3414" />
		<Location x="148786" y="46842" z="-3414" />
		<Location x="148786" y="46939" z="-3414" />
		<Location x="148786" y="47033" z="-3414" />
		<Location x="148786" y="47132" z="-3414" />
		<Location x="150114" y="46358" z="-3414" />
		<Location x="150114" y="46445" z="-3414" />
		<Location x="150114" y="46540" z="-3414" />
		<Location x="150114" y="46642" z="-3414" />
		<Location x="150114" y="46735" z="-3414" />
		<Location x="150114" y="46833" z="-3414" />
		<Location x="150114" y="46930" z="-3414" />
		<Location x="150114" y="47023" z="-3414" />
		<Location x="150114" y="47122" z="-3414" />
	</spawnPoints>
	<doorlist>
		<door doorId="24190001" />
		<door doorId="24190002" />
		<door doorId="24190003" />
		<door doorId="24190004" />
	</doorlist>
</instance>

=== danielbarion/L2JBlueHeart/game/data/xml/instances/OlympiadThreeBridgesArena.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance name="Three Bridges Arena" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/instance.xsd">
	<doorlist>
		<door doorId="17100101" />
		<door doorId="17100102" />
	</doorlist>
	<spawnlist>
		<group name="general">
			<spawn npcId="36402" x="-76760" y="-252461" z="-7741" heading="0" respawn="60" />
			<spawn npcId="36402" x="-74170" y="-252459" z="-7741" heading="0" respawn="60" />
		</group>
	</spawnlist>
</instance>

=== danielbarion/L2JBlueHeart/game/data/xml/instances/PailakaInjuredDragon.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance name="Pailaka73_77" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/instance.xsd">
	<activityTime val="90" />
	<allowSummon val="false" />
	<emptyDestroyTime val="3000" />
	<exitPoint x="147725" y="-56517" z="-2780" />
	<spawnlist>
	<group name="general">
		<spawn npcId="18635" x="122077" y="-46098" z="-2914" heading="5028" respawn="0" onKillDelay="0" />
		<spawn npcId="18635" x="122019" y="-45634" z="-2908" heading="64841" respawn="0" onKillDelay="0" />
		<spawn npcId="18635" x="117184" y="-51722" z="-2575" heading="55468" respawn="0" onKillDelay="0" />
		<spawn npcId="18635" x="116876" y="-51937" z="-2572" heading="59301" respawn="0" onKillDelay="0" />
		<spawn npcId="18636" x="122023" y="-45769" z="-2910" heading="63593" respawn="0" onKillDelay="0" />
		<spawn npcId="18636" x="122050" y="-45999" z="-2910" heading="1701" respawn="0" onKillDelay="0" />
		<spawn npcId="18636" x="117097" y="-51774" z="-2577" heading="51453" respawn="0" onKillDelay="0" />
		<spawn npcId="18636" x="116926" y="-51876" z="-2580" heading="56322" respawn="0" onKillDelay="0" />
		<spawn npcId="18637" x="123164" y="-52003" z="-2461" heading="13414" respawn="0" onKillDelay="0" />
		<spawn npcId="18637" x="123726" y="-51665" z="-2467" heading="6603" respawn="0" onKillDelay="0" />
		<spawn npcId="18637" x="111641" y="-56027" z="-2783" heading="43022" respawn="0" onKillDelay="0" />
		<spawn npcId="18637" x="123965" y="-51293" z="-2471" heading="5746" respawn="0" onKillDelay="0" />
		<spawn npcId="18637" x="125010" y="-50813" z="-2460" heading="1407" respawn="0" onKillDelay="0" />
		<spawn npcId="18637" x="122474" y="-42594" z="-3240" heading="49260" respawn="0" onKillDelay="0" />
		<spawn npcId="18637" x="121814" y="-41622" z="-3181" heading="5457" respawn="0" onKillDelay="0" />
		<spawn npcId="18637" x="121424" y="-41452" z="-3163" heading="41426" respawn="0" onKillDelay="0" />
		<spawn npcId="18637" x="121264" y="-41559" z="-3164" heading="47583" respawn="0" onKillDelay="0" />
		<spawn npcId="18637" x="121516" y="-43081" z="-3216" heading="61535" respawn="0" onKillDelay="0" />
		<spawn npcId="18642" x="117013" y="-51840" z="-2578" heading="55135" respawn="0" onKillDelay="0" />
		<spawn npcId="18642" x="122038" y="-45904" z="-2914" heading="771" respawn="0" onKillDelay="0" />
		<spawn npcId="18646" x="116054" y="-46439" z="-2637" heading="63477" respawn="0" onKillDelay="0" />
		<spawn npcId="18646" x="116057" y="-46521" z="-2644" heading="65025" respawn="0" onKillDelay="0" />
		<spawn npcId="18646" x="116503" y="-55918" z="-2449" heading="589" respawn="0" onKillDelay="0" />
		<spawn npcId="18646" x="116490" y="-56022" z="-2445" heading="61772" respawn="0" onKillDelay="0" />
		<spawn npcId="18646" x="116075" y="-50463" z="-2642" heading="53954" respawn="0" onKillDelay="0" />
		<spawn npcId="18646" x="116020" y="-50497" z="-2643" heading="55751" respawn="0" onKillDelay="0" />
		<spawn npcId="18647" x="108759" y="-53478" z="-2606" heading="25521" respawn="0" onKillDelay="0" />
		<spawn npcId="18647" x="108415" y="-53924" z="-2564" heading="18727" respawn="0" onKillDelay="0" />
		<spawn npcId="18647" x="107850" y="-52954" z="-2417" heading="21437" respawn="0" onKillDelay="0" />
		<spawn npcId="18649" x="111616" y="-43922" z="-2635" heading="60699" respawn="0" onKillDelay="0" />
		<spawn npcId="18649" x="110110" y="-39799" z="-1850" heading="46038" respawn="0" onKillDelay="0" />
		<spawn npcId="18649" x="109955" y="-39811" z="-1855" heading="48647" respawn="0" onKillDelay="0" />
		<spawn npcId="18649" x="111606" y="-43746" z="-2633" heading="62267" respawn="0" onKillDelay="0" />
		<spawn npcId="18649" x="111614" y="-44071" z="-2642" heading="63794" respawn="0" onKillDelay="0" />
		<spawn npcId="18650" x="109874" y="-39833" z="-1837" heading="48408" respawn="0" onKillDelay="0" />
		<spawn npcId="18650" x="111602" y="-43846" z="-2638" heading="63427" respawn="0" onKillDelay="0" />
		<spawn npcId="18650" x="110205" y="-39800" z="-1840" heading="46882" respawn="0" onKillDelay="0" />
		<spawn npcId="18650" x="111618" y="-44003" z="-2637" heading="59709" respawn="0" onKillDelay="0" />
		<spawn npcId="18650" x="111619" y="-44129" z="-2650" heading="2365" respawn="0" onKillDelay="0" />
		<spawn npcId="18651" x="111214" y="-55683" z="-2798" heading="27410" respawn="0" onKillDelay="0" />
		<spawn npcId="18651" x="111515" y="-55735" z="-2811" heading="24213" respawn="0" onKillDelay="0" />
		<spawn npcId="18651" x="110462" y="-54609" z="-2882" heading="24283" respawn="0" onKillDelay="0" />
		<spawn npcId="18651" x="111556" y="-54895" z="-2861" heading="20821" respawn="0" onKillDelay="0" />
		<spawn npcId="18653" x="116213" y="-50301" z="-2622" heading="50611" respawn="0" onKillDelay="0" />
		<spawn npcId="18653" x="116432" y="-55729" z="-2441" heading="65250" respawn="0" onKillDelay="0" />
		<spawn npcId="18653" x="115780" y="-50465" z="-2620" heading="52135" respawn="0" onKillDelay="0" />
		<spawn npcId="18653" x="116433" y="-56194" z="-2432" heading="927" respawn="0" onKillDelay="0" />
		<spawn npcId="18653" x="115997" y="-46271" z="-2637" heading="63732" respawn="0" onKillDelay="0" />
		<spawn npcId="18653" x="116063" y="-46680" z="-2658" heading="4323" respawn="0" onKillDelay="0" />
		<spawn npcId="18654" x="116155" y="-50420" z="-2635" heading="53262" respawn="0" onKillDelay="0" />
		<spawn npcId="18654" x="115952" y="-50528" z="-2646" heading="52507" respawn="0" onKillDelay="0" />
		<spawn npcId="18654" x="116481" y="-56108" z="-2437" heading="62531" respawn="0" onKillDelay="0" />
		<spawn npcId="18654" x="116499" y="-55822" z="-2449" heading="63477" respawn="0" onKillDelay="0" />
		<spawn npcId="18654" x="116056" y="-46341" z="-2630" heading="63791" respawn="0" onKillDelay="0" />
		<spawn npcId="18654" x="116084" y="-46587" z="-2651" heading="1141" respawn="0" onKillDelay="0" />
		<spawn npcId="18655" x="108892" y="-41031" z="-2204" heading="64381" respawn="0" onKillDelay="0" />
		<spawn npcId="18655" x="108877" y="-41436" z="-2144" heading="64321" respawn="0" onKillDelay="0" />
		<spawn npcId="18655" x="109326" y="-45781" z="-2235" heading="5945" respawn="0" onKillDelay="0" />
		<spawn npcId="18655" x="109584" y="-46100" z="-2263" heading="9356" respawn="0" onKillDelay="0" />
		<spawn npcId="18655" x="108862" y="-41323" z="-2174" heading="62422" respawn="0" onKillDelay="0" />
		<spawn npcId="18655" x="108886" y="-41185" z="-2196" heading="64884" respawn="0" onKillDelay="0" />
		<spawn npcId="18655" x="109458" y="-45980" z="-2263" heading="6915" respawn="0" onKillDelay="0" />
		<spawn npcId="18657" x="109393" y="-45893" z="-2253" heading="5549" respawn="0" onKillDelay="0" />
		<spawn npcId="18657" x="109516" y="-46032" z="-2268" heading="4362" respawn="0" onKillDelay="0" />
		<spawn npcId="18657" x="109272" y="-45665" z="-2210" heading="4731" respawn="0" onKillDelay="0" />
		<spawn npcId="18657" x="108888" y="-41114" z="-2195" heading="64256" respawn="0" onKillDelay="0" />
		<spawn npcId="18657" x="108878" y="-41260" z="-2188" heading="64876" respawn="0" onKillDelay="0" />
		<spawn npcId="18657" x="108869" y="-41376" z="-2163" heading="2280" respawn="0" onKillDelay="0" />
		<spawn npcId="18659" x="110023" y="-39802" z="-1852" heading="48655" respawn="0" onKillDelay="0" />
		<spawn npcId="32502" x="125524" y="-40946" z="-3718" heading="8279" respawn="0" />
		<spawn npcId="32509" x="110074" y="-41324" z="-2285" heading="33580" respawn="0" />
		<spawn npcId="32509" x="113745" y="-47565" z="-2593" heading="55710" respawn="0" />
	</group>
	</spawnlist>
</instance>
