=== danielbarion/L2JBlueHeart/game/data/xsd/item-mall.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="product" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="component" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="count" type="xs:positiveInteger" use="required" />
									<xs:attribute name="item_id" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:nonNegativeInteger" use="required" />
						<xs:attribute name="name" type="xs:normalizedString" use="required" />
						<xs:attribute name="count" type="xs:string" />
						<xs:attribute name="category" type="xs:nonNegativeInteger" />
						<xs:attribute name="price" type="xs:nonNegativeInteger" use="required" />
						<xs:attribute name="is_event" type="xs:boolean" />
						<xs:attribute name="is_best" type="xs:boolean" />
						<xs:attribute name="is_new" type="xs:boolean" />
						<xs:attribute name="sale_start_date" type="xs:normalizedString" />
						<xs:attribute name="sale_end_date" type="xs:normalizedString" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== danielbarion/L2JBlueHeart/game/data/xml/other/item-mall.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/item-mall.xsd">
    <!-- Buffs Scroll Bundle's -->
    <product id="1030061" name="Fighters Scroll Bundle 30 Sheet Pack" category="4" price="60">
        <component item_id="22087" count="30" />
    </product>
    <product id="1030062" name="Mages Scroll Bundle 30 Sheet Pack" category="4" price="60">
        <component item_id="22088" count="30" />
    </product>

    <!-- Buffs Scroll -->
    <product id="1080021" name="Wind Walk Scroll" category="2" price="1">
        <component item_id="22039" count="3" />
    </product>
    <product id="1080022" name="Haste Scroll" category="2" price="1">
        <component item_id="22040" count="3" />
    </product>
    <product id="1080023" name="Might Scroll" category="2" price="1">
        <component item_id="22041" count="3" />
    </product>
    <product id="1080024" name="Shield Scroll" category="2" price="1">
        <component item_id="22042" count="3" />
    </product>
    <product id="1080025" name="Death Whisper Scroll" category="2" price="1">
        <component item_id="22043" count="3" />
    </product>
    <product id="1080026" name="Guidance Scroll" category="2" price="1">
        <component item_id="22044" count="3" />
    </product>
    <product id="1080027" name="Empower Scroll" category="2" price="1">
        <component item_id="22045" count="3" />
    </product>
    <product id="1080028" name="Grater Acumen Scroll" category="2" price="1">
        <component item_id="22046" count="3" />
    </product>
    <product id="1080029" name="Vampiric Rage Scroll" category="2" price="1">
        <component item_id="22047" count="3" />
    </product>
    <product id="1080030" name="Bless the Body Scroll" category="2" price="1">
        <component item_id="22048" count="3" />
    </product>
    <product id="1080031" name="Berserker Spirit Scroll" category="2" price="1">
        <component item_id="22049" count="3" />
    </product>
    <product id="1080032" name="Magic Barrier Scroll" category="2" price="1">
        <component item_id="22050" count="3" />
    </product>
    <product id="1080033" name="Bless the Soul Scroll" category="2" price="1">
        <component item_id="22051" count="3" />
    </product>
    <product id="1080034" name="Clarity Scroll" category="2" price="1">
        <component item_id="22052" count="3" />
    </product>
    <product id="1080035" name="Wild Magic Scroll" category="2" price="1">
        <component item_id="22053" count="3" />
    </product>

    <!-- Fruit Cocktail -->
    <product id="1080199" name="Sweet Fruit Cocktail Pack" category="2" price="3" is_best="true">
        <component item_id="26011" count="1" />
    </product>
    <product id="1080200" name="Fresh Fruit Cocktail Pack" category="2" price="3" is_best="true">
        <component item_id="26012" count="1" />
    </product>

    <!-- Weapon Enchant Scroll -->
    <product id="1040319" name="Weapon Enchant Scroll - D Grade" category="1" price="1">
        <component item_id="955" count="1" />
    </product>
    <product id="1040321" name="Weapon Enchant Scroll - C Grade" category="1" price="5">
        <component item_id="951" count="1" />
    </product>
    <product id="1040323" name="Weapon Enchant Scroll - B Grade" category="1" price="10">
        <component item_id="947" count="1" />
    </product>
    <product id="1040325" name="Weapon Enchant Scroll - A Grade" category="1" price="20">
        <component item_id="729" count="1" />
    </product>
    <product id="1040327" name="Weapon Enchant Scroll - S Grade" category="1" price="30">
        <component item_id="959" count="1" />
    </product>

    <!-- Armor Enchant Scroll -->
    <product id="1040320" name="Armor Enchant Scroll - D Grade" category="1" price="1">
        <component item_id="956" count="1" />
    </product>
    <product id="1040322" name="Armor Enchant Scroll - C Grade" category="1" price="5">
        <component item_id="952" count="1" />
    </product>
    <product id="1040324" name="Armor Enchant Scroll - B Grade" category="1" price="10">
        <component item_id="948" count="1" />
    </product>
    <product id="1040326" name="Armor Enchant Scroll - A Grade" category="1" price="15">
        <component item_id="730" count="1" />
    </product>
    <product id="1040328" name="Armor Enchant Scroll - S Grade" category="1" price="25">
        <component item_id="960" count="1" />
    </product>

    <!-- Misc's -->
    <product id="1080185" name="Color Name" category="2" price="60">
        <component item_id="13021" count="1" />
    </product>
    <product id="1070236" name="Revita-Pop" category="2" price="5" is_best="true">
        <component item_id="20034" count="30" />
    </product>

    <!-- Feather of Blessing -->
    <product id="1080184" name="Feather of Blessing" category="2" price="10">
        <component item_id="10649" count="1" />
    </product>

    <!-- Soul Crystal -->
    <product id="1040275" name="Red Soul Crystal - Stage 12" category="1" price="10">
        <component item_id="5580" count="1" />
    </product>
    <product id="1040276" name="Green Soul Crystal - Stage 12" category="1" price="10">
        <component item_id="5581" count="1" />
    </product>
    <product id="1040277" name="Blue Soul Crystal - Stage 12" category="1" price="10">
        <component item_id="5582" count="1" />
    </product>
    <product id="1040278" name="Red Soul Crystal - Stage 13" category="1" price="20">
        <component item_id="5908" count="1" />
    </product>
    <product id="1040279" name="Green Soul Crystal - Stage 13" category="1" price="20">
        <component item_id="5911" count="1" />
    </product>
    <product id="1040280" name="Blue Soul Crystal - Stage 13" category="1" price="20">
        <component item_id="5914" count="1" />
    </product>
    <product id="1040281" name="Red Soul Crystal - Stage 14" category="1" price="30">
        <component item_id="9570" count="1" />
    </product>
    <product id="1040282" name="Blue Soul Crystal - Stage 14" category="1" price="30">
        <component item_id="9572" count="1" />
    </product>
    <product id="1040283" name="Green Soul Crystal - Stage 14" category="1" price="30">
        <component item_id="9571" count="1" />
    </product>

    <!-- Crystal of Element -->
    <product id="1070237" name="Crystal of Fire Pack" category="1" price="30">
        <component item_id="26005" count="1" />
    </product>
    <product id="1070238" name="Crystal of Water Pack" category="1" price="30">
        <component item_id="26006" count="1" />
    </product>
    <product id="1070239" name="Crystal of Earth Pack" category="1" price="30">
        <component item_id="26007" count="1" />
    </product>
    <product id="1070240" name="Crystal of Wind Pack" category="1" price="30">
        <component item_id="26008" count="1" />
    </product>
    <product id="1070241" name="Crystal of Darkness Pack" category="1" price="30">
        <component item_id="26009" count="1" />
    </product>
    <product id="1070242" name="Crystal of Sacred Pack" category="1" price="30">
        <component item_id="26010" count="1" />
    </product>

    <!-- Element Stone -->
    <product id="1070242" name="Fire Stone" category="1" price="6">
        <component item_id="9546" count="5" />
    </product>
    <product id="1070244" name="Water Stone" category="1" price="6">
        <component item_id="9547" count="5" />
    </product>
    <product id="1070245" name="Earth Stone" category="1" price="6">
        <component item_id="9548" count="5" />
    </product>
    <product id="1070246" name="Wind Stone" category="1" price="6">
        <component item_id="9549" count="5" />
    </product>
    <product id="1070247" name="Darkness Stone" category="1" price="6">
        <component item_id="9550" count="5" />
    </product>
    <product id="1070248" name="Holy Stone" category="1" price="6">
        <component item_id="9551" count="5" />
    </product>

    <!-- Beast Shots Pack -->
    <product id="1080140" name="Beast Soulshot Pack" category="2" price="1">
        <component item_id="20326" count="1" />
    </product>
    <product id="1080141" name="Beast Spiritshot Pack" category="2" price="1">
        <component item_id="20327" count="1" />
    </product>
    <product id="1080142" name="Blessed Beast Spiritshot Pack" category="2" price="1">
        <component item_id="20328" count="1" />
    </product>
    <product id="1080143" name="Beast Soulshot Large Pack" category="2" price="2">
        <component item_id="20329" count="1" />
    </product>
    <product id="1080144" name="Beast Spiritshot Large Pack" category="2" price="2">
        <component item_id="20330" count="1" />
    </product>
    <product id="1080145" name="Blessed Beast Spiritshot Large Pack" category="2" price="2">
        <component item_id="20331" count="1" />
    </product>

    <!-- Shots Pack -->
    <product id="1080063" name="Blessed Spiritshot Pack - B grade" category="2" price="3">
        <component item_id="22096" count="1" />
    </product>
    <product id="1080064" name="Blessed Spiritshot Pack - A grade" category="2" price="5">
        <component item_id="22097" count="1" />
    </product>
    <product id="1080065" name="Blessed Spiritshot Pack - S grade" category="2" price="10">
        <component item_id="22098" count="1" />
    </product>
    <product id="1080068" name="Spiritshot Pack -  B grade" category="2" price="3">
        <component item_id="22101" count="1" />
    </product>
    <product id="1080069" name="Spiritshot Pack - A grade" category="2" price="5">
        <component item_id="22102" count="1" />
    </product>
    <product id="1080070" name="Spiritshot Pack - S grade" category="2" price="10">
        <component item_id="22103" count="1" />
    </product>
