=== danielbarion/L2JBlueHeart/game/data/xsd/multisell.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="npcs" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="npc" minOccurs="1" maxOccurs="unbounded">
								<xs:simpleType>
									<xs:restriction base="xs:positiveInteger">
										<xs:minInclusive value="1" />
										<xs:maxInclusive value="65535" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="item" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="ingredient" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="count" type="xs:positiveInteger" use="required" />
									<xs:attribute name="id" type="xs:integer" use="required" />
									<xs:attribute name="maintainIngredient" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
							<xs:element name="production" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="count" type="xs:positiveInteger" use="required" />
									<xs:attribute name="id" type="xs:integer" use="required" />
									<xs:attribute name="enchantmentLevel" type="xs:integer" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="applyTaxes" type="xs:boolean" />
			<xs:attribute name="maintainEnchantment" type="xs:boolean" />
			<xs:attribute name="useRate" type="xs:token" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== danielbarion/L2JBlueHeart/game/data/multisell/custom/90004.xml
<?xml version='1.0' encoding='utf-8'?>

<!-- Created with Lineage II - Multisell Manager -->


<list maintainEnchantment="false"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../xsd/multisell.xsd">

	<!-- Mithril Breastplate -->
	<item>
		<ingredient id="57" count="1000000" />
		<production id="58" count="1" />
		<production id="59" count="1" />
		<production id="47" count="1" />
		<production id="628" count="1" />
	</item>

	<!-- Brigandine Tunic -->
	<item>
		<ingredient id="57" count="1000000" />
		<production id="352" count="1" />
		<production id="2378" count="1" />
		<production id="2411" count="1" />
		<production id="2425" count="1" />
		<production id="2449" count="1" />
		<production id="2493" count="1" />
	</item>

	<!-- Reinforced Leather Shirt -->
	<item>
		<ingredient id="57" count="1000000" />
		<production id="394" count="1" />
		<production id="416" count="1" />
		<production id="2422" count="1" />
		<production id="2446" count="1" />
	</item>

	<!-- Manticore Skin Shirt -->
	<item>
		<ingredient id="57" count="1000000" />
		<production id="395" count="1" />
		<production id="417" count="1" />
		<production id="2424" count="1" />
		<production id="2448" count="1" />
	</item>

	<!-- Tunic of Knowledge -->
	<item>
		<ingredient id="57" count="1000000" />
		<production id="436" count="1" />
		<production id="469" count="1" />
		<production id="2447" count="1" />
	</item>

	<!-- Mithril Tunic -->
	<item>
		<ingredient id="57" count="1000000" />
		<production id="437" count="1" />
		<production id="470" count="1" />
		<production id="2450" count="1" />
	</item>

	<!-- Clan Oath Armor -->
	<item>
		<ingredient id="57" count="3000000" />
		<production id="7851" count="1" />
		<production id="7853" count="1" />
		<production id="7852" count="1" />
		<production id="7850" count="1" />
	</item>

	<!-- Clan Oath Brigandine -->
	<item>
		<ingredient id="57" count="3000000" />
		<production id="7854" count="1" />
		<production id="7856" count="1" />
		<production id="7855" count="1" />
		<production id="7850" count="1" />
	</item>

	<!-- Clan Oath Aketon -->
	<item>
		<ingredient id="57" count="3000000" />
		<production id="7857" count="1" />
		<production id="7858" count="1" />
		<production id="7859" count="1" />
		<production id="7850" count="1" />
	</item>


</list>

=== danielbarion/L2JBlueHeart/game/data/multisell/318275004.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/multisell.xsd">
	<npcs>
		<npc>31827</npc> <!-- Adventure Guildsman -->
		<npc>31828</npc> <!-- Adventure Guildsman -->
		<npc>31829</npc> <!-- Adventure Guildsman -->
		<npc>31830</npc> <!-- Adventure Guildsman -->
		<npc>31831</npc> <!-- Adventure Guildsman -->
	</npcs>
	<item>
		<!-- Memento Mori -->
		<ingredient count="204" id="9814" />
		<!-- Dragon Heart -->
		<ingredient count="56" id="9815" />
		<!-- Earth Egg -->
		<ingredient count="224" id="9816" />
		<!-- Nonliving Nucleus -->
		<ingredient count="112" id="9817" />
		<!-- Crystal Staff -->
		<production count="1" id="192" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="256" id="9814" />
		<!-- Dragon Heart -->
		<ingredient count="70" id="9815" />
		<!-- Earth Egg -->
		<ingredient count="280" id="9816" />
		<!-- Nonliving Nucleus -->
		<ingredient count="140" id="9817" />
		<!-- Cursed Staff -->
		<production count="1" id="195" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="414" id="9814" />
		<!-- Dragon Heart -->
		<ingredient count="112" id="9815" />
		<!-- Earth Egg -->
		<ingredient count="452" id="9816" />
		<!-- Nonliving Nucleus -->
		<ingredient count="226" id="9817" />
		<!-- Stick of Eternity -->
		<production count="1" id="196" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="590" id="9814" />
		<!-- Dragon Heart -->
		<ingredient count="160" id="9815" />
		<!-- Earth Egg -->
		<ingredient count="644" id="9816" />
		<!-- Nonliving Nucleus -->
		<ingredient count="322" id="9817" />
		<!-- Ghoul's Staff -->
		<production count="1" id="205" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="590" id="9814" />
		<!-- Dragon Heart -->
		<ingredient count="160" id="9815" />
		<!-- Earth Egg -->
		<ingredient count="644" id="9816" />
		<!-- Nonliving Nucleus -->
		<ingredient count="322" id="9817" />
		<!-- Ecliptic Axe -->
		<production count="1" id="7891" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="772" id="9814" />
		<!-- Dragon Heart -->
		<ingredient count="232" id="9815" />
		<!-- Earth Egg -->
		<ingredient count="772" id="9816" />
		<!-- Nonliving Nucleus -->
		<ingredient count="540" id="9817" />
		<!-- Angelic Essence -->
		<ingredient count="464" id="9818" />
		<!-- Sprite's Staff -->
		<production count="1" id="92" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="772" id="9814" />
		<!-- Dragon Heart -->
		<ingredient count="232" id="9815" />
		<!-- Earth Egg -->
		<ingredient count="772" id="9816" />
		<!-- Nonliving Nucleus -->
		<ingredient count="540" id="9817" />
		<!-- Angelic Essence -->
		<ingredient count="464" id="9818" />
		<!-- Spell Breaker -->
		<production count="1" id="7892" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="1236" id="9814" />
		<!-- Dragon Heart -->
		<ingredient count="372" id="9815" />
		<!-- Earth Egg -->
		<ingredient count="1236" id="9816" />
		<!-- Nonliving Nucleus -->
		<ingredient count="864" id="9817" />
		<!-- Angelic Essence -->
		<ingredient count="744" id="9818" />
		<!-- Staff of Evil Spirits -->
		<production count="1" id="210" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="1236" id="9814" />
		<!-- Dragon Heart -->
		<ingredient count="372" id="9815" />
		<!-- Earth Egg -->
		<ingredient count="1236" id="9816" />
		<!-- Nonliving Nucleus -->
		<ingredient count="864" id="9817" />
		<!-- Angelic Essence -->
		<ingredient count="744" id="9818" />
		<!-- Kaim Vanul's Bones -->
		<production count="1" id="7893" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="14" id="9814" />
		<!-- Earth Egg -->
		<ingredient count="14" id="9816" />
		<!-- Angelic Essence -->
		<ingredient count="2" id="9818" />
		<!-- Chain Boots -->
		<production count="1" id="2429" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="14" id="9814" />
		<!-- Earth Egg -->
		<ingredient count="14" id="9816" />
		<!-- Angelic Essence -->
		<ingredient count="2" id="9818" />
		<!-- Reinforced Mithril Boots -->
		<production count="1" id="62" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="14" id="9814" />
		<!-- Earth Egg -->
		<ingredient count="14" id="9816" />
		<!-- Angelic Essence -->
		<ingredient count="2" id="9818" />
		<!-- Karmian Boots -->
		<production count="1" id="2430" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="14" id="9814" />
		<!-- Earth Egg -->
		<ingredient count="14" id="9816" />
		<!-- Angelic Essence -->
		<ingredient count="2" id="9818" />
		<!-- Dwarven Chain Boots -->
		<production count="1" id="2432" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="14" id="9814" />
		<!-- Earth Egg -->
		<ingredient count="14" id="9816" />
		<!-- Angelic Essence -->
		<ingredient count="2" id="9818" />
		<!-- Boots of Seal -->
		<production count="1" id="2433" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="18" id="9814" />
		<!-- Earth Egg -->
		<ingredient count="18" id="9816" />
		<!-- Angelic Essence -->
		<ingredient count="4" id="9818" />
		<!-- Rind Leather Boots -->
		<production count="1" id="2434" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="28" id="9814" />
		<!-- Earth Egg -->
		<ingredient count="30" id="9816" />
		<!-- Angelic Essence -->
		<ingredient count="6" id="9818" />
		<!-- Composite Boots -->
		<production count="1" id="64" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="32" id="9814" />
		<!-- Earth Egg -->
		<ingredient count="34" id="9816" />
		<!-- Angelic Essence -->
		<ingredient count="6" id="9818" />
		<!-- Theca Leather Boots -->
		<production count="1" id="2436" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="40" id="9814" />
		<!-- Earth Egg -->
		<ingredient count="44" id="9816" />
		<!-- Angelic Essence -->
		<ingredient count="8" id="9818" />
		<!-- Full Plate Boots -->
		<production count="1" id="2438" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="40" id="9814" />
		<!-- Earth Egg -->
		<ingredient count="44" id="9816" />
		<!-- Angelic Essence -->
		<ingredient count="8" id="9818" />
		<!-- Drake Leather Boots -->
		<production count="1" id="2437" />
	</item>
	<item>
		<!-- Memento Mori -->
		<ingredient count="4" id="9814" />
		<!-- Dragon Heart -->
		<ingredient count="4" id="9815" />
		<!-- Earth Egg -->
		<ingredient count="4" id="9816" />
		<!-- Nonliving Nucleus -->
		<ingredient count="4" id="9817" />
		<!-- Angelic Essence -->
		<ingredient count="4" id="9818" />
		<!-- Adena -->
		<ingredient count="600000" id="57" />
		<!-- Transformation Sealbook: Dragon Bomber -->
		<production count="1" id="9655" />
	</item>
</list>

=== danielbarion/L2JBlueHeart/game/data/multisell/custom/10068.xml
<?xml version='1.0' encoding='utf-8'?>

<!-- S-84 Weapon -->


<list maintainEnchantment="true"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../xsd/multisell.xsd">

	<!-- Vesper Avenger - Health -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14137" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Avenger - HP Drain -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14136" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Avenger - HP Regeneration -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14138" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Buster - Acumen -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14125" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Buster - Magic Hold -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14126" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Buster - Mana Up -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14124" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Caster -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14142" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Caster - Mana Up -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14144" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Caster - MP Regeneration -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14143" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Cutter -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14120" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Cutter - Haste -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14118" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Cutter - Health -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14119" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Fighter - Critical Stun -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14132" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Fighter - Focus -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14130" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Fighter - Health -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14131" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Nagan - Focus -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14159" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Nagan - Health -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14158" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Nagan - Haste -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14157" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Pincer - Focus -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14153" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Pincer - Haste -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14151" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Pincer - Health -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14152" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Retributer - Health -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14140" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Retributer - HP Drain -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14141" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Retributer - HP Regeneration -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14139" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Shaper - Critical Damage -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14127" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Shaper - HP Drain -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14128" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Shaper - Haste -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14129" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Sheutjeh - Cheap Shot -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14154" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Sheutjeh - Critical Slow -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14156" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Sheutjeh - Focus -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14155" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Singer - Empower -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14145" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Singer - Magic Hold -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14147" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Singer - MP Regeneration -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14146" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Slasher - Focus -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14123" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Slasher - Haste -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14121" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Slasher - Health -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14122" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Stormer - Guidance -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14134" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Stormer - Haste -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14135" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Stormer - Health -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14133" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Thrower - Cheap Shot -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14148" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Thrower - Focus -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14149" count="1" enchantmentLevel="25" />
	</item>

	<!-- Vesper Thrower - Critical Slow -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="14150" count="1" enchantmentLevel="25" />
	</item>

	<!-- vesper dual sword -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="52" count="1" enchantmentLevel="25" />
	</item>
	<!-- vesper dual dagger -->
	<item>
		<ingredient id="40000" count="20" />
		<production id="13884" count="1" enchantmentLevel="25" />
	</item>

</list>
