=== danielbarion/L2JBlueHeart/game/data/xsd/optionsData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="option" maxOccurs="100" minOccurs="1">
					<xs:complexType>
						<xs:sequence maxOccurs="1" minOccurs="1">
							<xs:element name="for" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="unbounded" minOccurs="1">
										<xs:element name="add" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="order" type="xs:byte" use="optional" />
												<xs:attribute name="stat" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="accCombat" />
															<xs:enumeration value="critDmgAdd" />
															<xs:enumeration value="CON" />
															<xs:enumeration value="darkRes" />
															<xs:enumeration value="DEX" />
															<xs:enumeration value="earthRes" />
															<xs:enumeration value="fireRes" />
															<xs:enumeration value="holyRes" />
															<xs:enumeration value="INT" />
															<xs:enumeration value="mAtk" />
															<xs:enumeration value="maxCp" />
															<xs:enumeration value="maxHp" />
															<xs:enumeration value="maxMp" />
															<xs:enumeration value="mCritRate" />
															<xs:enumeration value="mDef" />
															<xs:enumeration value="MEN" />
															<xs:enumeration value="pAtk" />
															<xs:enumeration value="pDef" />
															<xs:enumeration value="physicalSkillPower" />
															<xs:enumeration value="critRate" />
															<xs:enumeration value="regCp" />
															<xs:enumeration value="regHp" />
															<xs:enumeration value="regMp" />
															<xs:enumeration value="rEvas" />
															<xs:enumeration value="runSpd" />
															<xs:enumeration value="STR" />
															<xs:enumeration value="waterRes" />
															<xs:enumeration value="windRes" />
															<xs:enumeration value="WIT" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute type="xs:decimal" name="val" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="mul" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="order" type="xs:byte" use="optional" />
												<xs:attribute name="stat" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="mpConsume" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="val" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="active_skill" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="id" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="65535" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="level" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="99" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="passive_skill" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="id" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="65535" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="level" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="99" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="attack_skill" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="id" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="65535" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="level" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="99" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="chance" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:decimal">
												<xs:minInclusive value="1.0" />
												<xs:maxInclusive value="100.0" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="critical_skill" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="id" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="65535" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="level" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="99" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="chance" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:decimal">
												<xs:minInclusive value="1.0" />
												<xs:maxInclusive value="100.0" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="magic_skill" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="id" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="65535" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="level" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="99" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="chance" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:decimal">
												<xs:minInclusive value="1.0" />
												<xs:maxInclusive value="100.0" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:positiveInteger">
									<xs:minInclusive value="1" />
									<xs:maxInclusive value="65535" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute type="xs:token" name="name" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== danielbarion/L2JBlueHeart/game/data/xml/stats/options/20900-20999.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/optionsData.xsd">
	<option id="20900" name="o_w_80_2g_20">
		<!-- P. Def. increases by 9.15. HP Regen increases by 0.1. -->
		<for>
			<add stat="pDef" val="9.153" />
			<add stat="regHp" val="0.101" />
		</for>
	</option>
	<option id="20901" name="o_w_80_2g_21">
		<!-- P. Def. increases by 9.15. MP Regen increases by 0.07. -->
		<for>
			<add stat="pDef" val="9.153" />
			<add stat="regMp" val="0.065" />
		</for>
	</option>
	<option id="20902" name="o_w_80_2g_22">
		<!-- P. Def. increases by 9.15. CP Regen increases by 0.1. -->
		<for>
			<add stat="pDef" val="9.153" />
			<add stat="regCp" val="0.101" />
		</for>
	</option>
	<option id="20903" name="o_w_80_2g_23">
		<!-- P. Def. increases by 9.15. Evasion increases by 0.68. -->
		<for>
			<add stat="pDef" val="9.153" />
			<add stat="rEvas" val="0.677" />
		</for>
	</option>
	<option id="20904" name="o_w_80_2g_24">
		<!-- P. Def. increases by 9.15. Accuracy increases by 0.68. -->
		<for>
			<add stat="pDef" val="9.153" />
			<add stat="accCombat" val="0.677" />
		</for>
	</option>
	<option id="20905" name="o_w_80_2g_25">
		<!-- P. Def. increases by 9.15. Critical increases by 5.28. -->
		<for>
			<add stat="pDef" val="9.153" />
			<add stat="critRate" val="5.28" />
		</for>
	</option>
	<option id="20906" name="o_w_80_2g_26">
		<!-- M. Def. increases by 7.22. Max HP increases by 18.34 -->
		<for>
			<add stat="mDef" val="7.222" />
			<add stat="maxHp" val="18.341" />
		</for>
	</option>
	<option id="20907" name="o_w_80_2g_27">
		<!-- M. Def. increases by 7.22. Max HP increases by 21.82. -->
		<for>
			<add stat="mDef" val="7.222" />
			<add stat="maxMp" val="21.823" />
		</for>
	</option>
	<option id="20908" name="o_w_80_2g_28">
		<!-- M. Def. increases by 7.22. Max CP increases by 27.51. -->
		<for>
			<add stat="mDef" val="7.222" />
			<add stat="maxCp" val="27.512" />
		</for>
	</option>
	<option id="20909" name="o_w_80_2g_29">
		<!-- M. Def. increases by 7.22. P. Atk. increases by 4.95. -->
		<for>
			<add stat="mDef" val="7.222" />
			<add stat="pAtk" val="4.954" />
		</for>
	</option>
	<option id="20910" name="o_w_80_2g_30">
		<!-- M. Def. increases by 7.22. M. Atk. increases by 6.11. -->
		<for>
			<add stat="mDef" val="7.222" />
			<add stat="mAtk" val="6.106" />
		</for>
	</option>
	<option id="20911" name="o_w_80_2g_31">
		<!-- M. Def. increases by 7.22. HP Regen increases by 0.1. -->
		<for>
			<add stat="mDef" val="7.222" />
			<add stat="regHp" val="0.101" />
		</for>
	</option>
	<option id="20912" name="o_w_80_2g_32">
		<!-- M. Def. increases by 7.22. MP Regen increases by 0.07. -->
		<for>
			<add stat="mDef" val="7.222" />
			<add stat="regMp" val="0.065" />
		</for>
	</option>
	<option id="20913" name="o_w_80_2g_33">
		<!-- M. Def. increases by 7.22. CP Regen increases by 0.1. -->
		<for>
			<add stat="mDef" val="7.222" />
			<add stat="regCp" val="0.101" />
		</for>
	</option>
	<option id="20914" name="o_w_80_2g_34">
		<!-- M. Def. increases by 7.22. Evasion increases by 0.68. -->
		<for>
			<add stat="mDef" val="7.222" />
			<add stat="rEvas" val="0.677" />
		</for>
	</option>
	<option id="20915" name="o_w_80_2g_35">
		<!-- M. Def. increases by 7.22. Accuracy increases by 0.68. -->
		<for>
			<add stat="mDef" val="7.222" />
			<add stat="accCombat" val="0.677" />
		</for>
	</option>
	<option id="20916" name="o_w_80_2g_36">
		<!-- M. Def. increases by 7.22. Critical increases by 5.28. -->
		<for>
			<add stat="mDef" val="7.222" />
			<add stat="critRate" val="5.28" />
		</for>
	</option>
	<option id="20917" name="o_w_80_2g_37">
		<!-- Max HP increases by 21.4 Max HP increases by 21.82. -->
		<for>
			<add stat="maxHp" val="21.398" />
			<add stat="maxMp" val="21.823" />
		</for>
	</option>
	<option id="20918" name="o_w_80_2g_38">
		<!-- Max HP increases by 21.4 Max CP increases by 27.51. -->
		<for>
			<add stat="maxHp" val="21.398" />
			<add stat="maxCp" val="27.512" />
		</for>
	</option>
	<option id="20919" name="o_w_80_2g_39">
		<!-- Max HP increases by 21.4 P. Atk. increases by 4.95. -->
		<for>
			<add stat="maxHp" val="21.398" />
			<add stat="pAtk" val="4.954" />
		</for>
	</option>
	<option id="20920" name="o_w_80_2g_40">
		<!-- Max HP increases by 21.4 M. Atk. increases by 6.11. -->
		<for>
			<add stat="maxHp" val="21.398" />
			<add stat="mAtk" val="6.106" />
		</for>
	</option>
	<option id="20921" name="o_w_80_2g_41">
		<!-- Max HP increases by 21.4 HP Regen increases by 0.1. -->
		<for>
			<add stat="maxHp" val="21.398" />
			<add stat="regHp" val="0.101" />
		</for>
	</option>
	<option id="20922" name="o_w_80_2g_42">
		<!-- Max HP increases by 21.4 MP Regen increases by 0.07. -->
		<for>
			<add stat="maxHp" val="21.398" />
			<add stat="regMp" val="0.065" />
		</for>
	</option>
	<option id="20923" name="o_w_80_2g_43">
		<!-- Max HP increases by 21.4 CP Regen increases by 0.1. -->
		<for>
			<add stat="maxHp" val="21.398" />
			<add stat="regCp" val="0.101" />
		</for>
	</option>
	<option id="20924" name="o_w_80_2g_44">
		<!-- Max HP increases by 21.4 Evasion increases by 0.68. -->
		<for>
			<add stat="maxHp" val="21.398" />
			<add stat="rEvas" val="0.677" />
		</for>
	</option>
	<option id="20925" name="o_w_80_2g_45">
		<!-- Max HP increases by 21.4 Accuracy increases by 0.68. -->
		<for>
			<add stat="maxHp" val="21.398" />
			<add stat="accCombat" val="0.677" />
		</for>
	</option>
	<option id="20926" name="o_w_80_2g_46">
		<!-- Max HP increases by 21.4 Critical increases by 5.28. -->
		<for>
			<add stat="maxHp" val="21.398" />
			<add stat="critRate" val="5.28" />
		</for>
	</option>
	<option id="20927" name="o_w_80_2g_47">
		<!-- Max HP increases by 25.46. Max CP increases by 27.51. -->
		<for>
			<add stat="maxMp" val="25.461" />
			<add stat="maxCp" val="27.512" />
		</for>
	</option>
	<option id="20928" name="o_w_80_2g_48">
		<!-- Max HP increases by 25.46. P. Atk. increases by 4.95. -->
		<for>
			<add stat="maxMp" val="25.461" />
			<add stat="pAtk" val="4.954" />
		</for>
	</option>
	<option id="20929" name="o_w_80_2g_49">
		<!-- Max HP increases by 25.46. M. Atk. increases by 6.11. -->
		<for>
			<add stat="maxMp" val="25.461" />
			<add stat="mAtk" val="6.106" />
		</for>
	</option>
	<option id="20930" name="o_w_80_2g_50">
		<!-- Max HP increases by 25.46. HP Regen increases by 0.1. -->
		<for>
			<add stat="maxMp" val="25.461" />
			<add stat="regHp" val="0.101" />
		</for>
	</option>
	<option id="20931" name="o_w_80_2g_51">
		<!-- Max HP increases by 25.46. MP Regen increases by 0.07. -->
		<for>
			<add stat="maxMp" val="25.461" />
			<add stat="regMp" val="0.065" />
		</for>
	</option>
	<option id="20932" name="o_w_80_2g_52">
		<!-- Max HP increases by 25.46. CP Regen increases by 0.1. -->
		<for>
			<add stat="maxMp" val="25.461" />
			<add stat="regCp" val="0.101" />
		</for>
	</option>
	<option id="20933" name="o_w_80_2g_53">
		<!-- Max HP increases by 25.46. Evasion increases by 0.68. -->
		<for>
			<add stat="maxMp" val="25.461" />
			<add stat="rEvas" val="0.677" />
		</for>
	</option>
	<option id="20934" name="o_w_80_2g_54">
		<!-- Max HP increases by 25.46. Accuracy increases by 0.68. -->
		<for>
			<add stat="maxMp" val="25.461" />
			<add stat="accCombat" val="0.677" />
		</for>
	</option>
	<option id="20935" name="o_w_80_2g_55">
		<!-- Max HP increases by 25.46. Critical increases by 5.28. -->
		<for>
			<add stat="maxMp" val="25.461" />
			<add stat="critRate" val="5.28" />
		</for>
	</option>
	<option id="20936" name="o_w_80_2g_56">
		<!-- Max CP increases by 32.1. P. Atk. increases by 4.95. -->
		<for>
			<add stat="maxCp" val="32.097" />
			<add stat="pAtk" val="4.954" />
		</for>
	</option>
	<option id="20937" name="o_w_80_2g_57">
		<!-- Max CP increases by 32.1. M. Atk. increases by 6.11. -->
		<for>
			<add stat="maxCp" val="32.097" />
			<add stat="mAtk" val="6.106" />
		</for>
	</option>
	<option id="20938" name="o_w_80_2g_58">
		<!-- Max CP increases by 32.1. HP Regen increases by 0.1. -->
		<for>
			<add stat="maxCp" val="32.097" />
			<add stat="regHp" val="0.101" />
		</for>
	</option>
	<option id="20939" name="o_w_80_2g_59">
		<!-- Max CP increases by 32.1. MP Regen increases by 0.07. -->
		<for>
			<add stat="maxCp" val="32.097" />
			<add stat="regMp" val="0.065" />
		</for>
	</option>
	<option id="20940" name="o_w_80_2g_60">
		<!-- Max CP increases by 32.1. CP Regen increases by 0.1. -->
		<for>
			<add stat="maxCp" val="32.097" />
			<add stat="regCp" val="0.101" />
		</for>
	</option>
	<option id="20941" name="o_w_80_2g_61">
		<!-- Max CP increases by 32.1. Evasion increases by 0.68. -->
		<for>
			<add stat="maxCp" val="32.097" />
			<add stat="rEvas" val="0.677" />
		</for>
	</option>
	<option id="20942" name="o_w_80_2g_62">
		<!-- Max CP increases by 32.1. Accuracy increases by 0.68. -->
		<for>
			<add stat="maxCp" val="32.097" />
			<add stat="accCombat" val="0.677" />
		</for>
	</option>
	<option id="20943" name="o_w_80_2g_63">
		<!-- Max CP increases by 32.1. Critical increases by 5.28. -->
		<for>
			<add stat="maxCp" val="32.097" />
			<add stat="critRate" val="5.28" />
		</for>
	</option>
	<option id="20944" name="o_w_80_2g_64">
		<!-- P. Atk. increases by 5.78. M. Atk. increases by 6.11. -->
		<for>
			<add stat="pAtk" val="5.78" />
			<add stat="mAtk" val="6.106" />
		</for>
	</option>
	<option id="20945" name="o_w_80_2g_65">
		<!-- P. Atk. increases by 5.78. HP Regen increases by 0.1. -->
		<for>
			<add stat="pAtk" val="5.78" />
			<add stat="regHp" val="0.101" />
		</for>
	</option>
	<option id="20946" name="o_w_80_2g_66">
		<!-- P. Atk. increases by 5.78. MP Regen increases by 0.07. -->
		<for>
			<add stat="pAtk" val="5.78" />
			<add stat="regMp" val="0.065" />
		</for>
	</option>
	<option id="20947" name="o_w_80_2g_67">
		<!-- P. Atk. increases by 5.78. CP Regen increases by 0.1. -->
		<for>
