=== danielbarion/L2JBlueHeart/game/data/xsd/dressme/armor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="dress" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="set">
								<xs:complexType>
									<xs:attribute name="chest" type="xs:int"></xs:attribute>
									<xs:attribute name="legs" type="xs:int"></xs:attribute>
									<xs:attribute name="gloves" type="xs:int"></xs:attribute>
									<xs:attribute name="feet" type="xs:int"></xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="price">
								<xs:complexType>
									<xs:attribute name="id" type="xs:int"></xs:attribute>
									<xs:attribute name="count" type="xs:int"></xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:int"></xs:attribute>
						<xs:attribute name="name" type="xs:string"></xs:attribute>
						<xs:attribute name="type" type="xs:string"></xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== danielbarion/L2JBlueHeart/game/data/xml/sunrise/dressme/armor.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/dressme/armor.xsd">
	<dress id="1" name="Zubei's Breastplate Set" type="HEAVY">
		<set chest="357" legs="383" gloves="5710" feet="5726" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="2" name="Avadon Breastplate Set" type="HEAVY">
		<set chest="2376" legs="2379" gloves="5714" feet="5730" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="3" name="Zubei's Leather Shirt Set" type="LIGHT">
		<set chest="2384" legs="2388" gloves="5711" feet="5727" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="4" name="Avadon Leather Armor Set" type="LIGHT">
		<set chest="2390" legs="-1" gloves="5715" feet="5731" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="5" name="Zubei Set" type="ROBE">
		<set chest="2397" legs="2402" gloves="5712" feet="5728" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="6" name="Avadon Robe Set" type="ROBE">
		<set chest="2406" legs="-1" gloves="5716" feet="5732" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="7" name="Blue Wolf Breastplate Set" type="HEAVY">
		<set chest="358" legs="2380" gloves="5718" feet="5734" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="8" name="Doom Armor Set" type="HEAVY">
		<set chest="2381" legs="-1" gloves="5722" feet="5738" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="9" name="Blue Wolf Leather Armor Set" type="LIGHT">
		<set chest="2391" legs="-1" gloves="5719" feet="5735" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="10" name="LeatherDoom Set" type="LIGHT">
		<set chest="2392" legs="-1" gloves="5723" feet="5739" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="11" name="Blue Wolf Tunic Set" type="ROBE">
		<set chest="2398" legs="2403" gloves="5720" feet="5736" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="12" name="Doom Set" type="HEAVY">
		<set chest="2399" legs="2404" gloves="5724" feet="5740" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="13" name="Dark Crystal Breastplate Set" type="HEAVY">
		<set chest="365" legs="388" gloves="5765" feet="5777" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="14" name="Tallum Armor Set" type="HEAVY">
		<set chest="2382" legs="-1" gloves="5768" feet="5780" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="15" name="Dark Crystal Leather Armor Set" type="LIGHT">
		<set chest="2385" legs="2389" gloves="5766" feet="5778" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="16" name="Tallum Leather Armor Set" type="LIGHT">
		<set chest="2393" legs="-1" gloves="5769" feet="5781" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="17" name="Tallum Tunic Set" type="ROBE">
		<set chest="2400" legs="2405" gloves="5770" feet="5782" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="18" name="Dark Crystal Robe Set" type="ROBE">
		<set chest="2407" legs="-1" gloves="5767" feet="5779" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="19" name="Nightmare Set" type="HEAVY">
		<set chest="374" legs="-1" gloves="5771" feet="5783" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="20" name="Majestic Armor Set" type="HEAVY">
		<set chest="2383" legs="-1" gloves="5774" feet="5786" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="21" name="Nightmarish Leather Armor Set" type="LIGHT">
		<set chest="2394" legs="-1" gloves="5772" feet="5784" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="22" name="Majestic Leather Armor Set" type="LIGHT">
		<set chest="2395" legs="-1" gloves="5775" feet="5787" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="23" name="Nightmare Robe Set" type="ROBE">
		<set chest="2408" legs="-1" gloves="5773" feet="5785" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="24" name="Majestic Robe Set" type="ROBE">
		<set chest="2409" legs="-1" gloves="5776" feet="5788" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="25" name="Imperial Crusader Breastplate Set" type="HEAVY">
		<set chest="6373" legs="6374" gloves="6375" feet="6376" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="26" name="Draconic Leather Armor Set" type="LIGHT">
		<set chest="6379" legs="-1" gloves="6380" feet="6381" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="27" name="Major Arcana Robe Set" type="ROBE">
		<set chest="6383" legs="-1" gloves="6384" feet="6385" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="28" name="Clan Oath Armor Set" type="HEAVY">
		<set chest="7851" legs="-1" gloves="7852" feet="7853" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="29" name="Clan Oath Brigandine Set" type="LIGHT">
		<set chest="7854" legs="-1" gloves="7855" feet="7856" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="30" name="Clan Oath Aketon Set" type="ROBE">
		<set chest="7857" legs="-1" gloves="7858" feet="7859" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="31" name="Apella Armor Set" type="HEAVY">
		<set chest="7861" legs="-1" gloves="7862" feet="7863" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="32" name="Apella Brigandine Set" type="LIGHT">
		<set chest="7864" legs="-1" gloves="7865" feet="7866" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="33" name="Apella Doublet Set" type="ROBE">
		<set chest="7867" legs="-1" gloves="7868" feet="7869" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="34" name="Dynasty Breast Plate Set" type="HEAVY">
		<set chest="9417" legs="9421" gloves="9423" feet="9424" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="35" name="Dynasty Breast Plate Set" type="HEAVY">
		<set chest="9418" legs="9421" gloves="9423" feet="9424" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="36" name="Dynasty Breast Plate Set" type="HEAVY">
		<set chest="9419" legs="9421" gloves="9423" feet="9424" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="37" name="Dynasty Breast Plate Set" type="HEAVY">
		<set chest="9420" legs="9421" gloves="9423" feet="9424" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="38" name="Dynasty Leather Armor Set" type="LIGHT">
		<set chest="9426" legs="9428" gloves="9430" feet="9431" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="39" name="Dynasty Leather Armor Set" type="LIGHT">
		<set chest="9427" legs="9428" gloves="9430" feet="9431" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="40" name="Dynasty Tunic Set" type="ROBE">
		<set chest="9433" legs="9437" gloves="9439" feet="9440" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="41" name="Dynasty Tunic Set" type="ROBE">
		<set chest="9434" legs="9437" gloves="9439" feet="9440" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="42" name="Dynasty Tunic Set" type="ROBE">
		<set chest="9435" legs="9437" gloves="9439" feet="9440" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="43" name="Dynasty Tunic Set" type="ROBE">
		<set chest="9436" legs="9437" gloves="9439" feet="9440" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="44" name="Improved Apella Armor Set" type="HEAVY">
		<set chest="9831" legs="-1" gloves="9832" feet="9833" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="45" name="Improved Apella Brigandine Set" type="LIGHT">
		<set chest="9834" legs="-1" gloves="9835" feet="9836" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="46" name="Improved Apella Doublet Set" type="ROBE">
		<set chest="9837" legs="-1" gloves="9838" feet="9839" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="47" name="Dynasty Breast Plate Set" type="HEAVY">
		<set chest="9416" legs="9421" gloves="9423" feet="9424" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="48" name="Dynasty Leather Armor Set" type="LIGHT">
		<set chest="9425" legs="9428" gloves="9430" feet="9431" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="49" name="Dynasty Tunic Set" type="ROBE">
		<set chest="9432" legs="9437" gloves="9439" feet="9440" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="50" name="Dynasty Leather Armor Set" type="LIGHT">
		<set chest="10126" legs="9428" gloves="9430" feet="9431" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="51" name="Dynasty Leather Armor Set" type="LIGHT">
		<set chest="10127" legs="9428" gloves="9430" feet="9431" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="52" name="Dynasty Leather Armor Set" type="LIGHT">
		<set chest="10168" legs="9428" gloves="9430" feet="9431" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="53" name="Dynasty Leather Armor Set" type="LIGHT">
		<set chest="10214" legs="9428" gloves="9430" feet="9431" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="54" name="Dynasty Platinum Plate Set" type="HEAVY">
		<set chest="10228" legs="9421" gloves="9423" feet="9424" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="55" name="Dynasty Platinum Plate Set" type="HEAVY">
		<set chest="10229" legs="9421" gloves="9423" feet="9424" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="56" name="Dynasty Platinum Plate Set" type="HEAVY">
		<set chest="10230" legs="9421" gloves="9423" feet="9424" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="57" name="Dynasty Platinum Plate Set" type="HEAVY">
		<set chest="10231" legs="9421" gloves="9423" feet="9424" />
		<price id="57" count="2000000000" />
	</dress>
	<dress id="58" name="Dynasty Jewel Leather Mail Set" type="LIGHT">
		<set chest="10233" legs="9428" gloves="9430" feet="9431" />
		<price id="57" count="2000000000" />
	</dress>
